### PR TITLE
update to allow PHP 8

### PR DESCRIPTION
**Pull request by dutchie027**
Simply adds the logical or to allow for PHP 7.2 or PHP 8.0 version(s)

### CODE REVIEW

**Comment by dutchie027** [comment]
changing to also include in travis

**Comment by duncan3dc** [comment]
I'm going to replace Travis with github actions soon, so don't worry about it. Also no need for a separate PR to include Travis anyway

**Comment by dutchie027** [comment]
Sounds good. Do you know when you plan on doing that or bumping versions to support PHP 8.X?

**Comment by duncan3dc** [comment]
I've just pushed an update to switch to GitHub actions today. I'll take a look this week at upgrading the various libraries and adding support for 8. I'd like to keep 7.3 for now if I can, but I'll see what the upgrades kick up

**Comment by dutchie027** [comment]
Just logically OR it with composer and support both 7.x or 8.x. I'm happy to test it for the 8.x. Problem is there are quite a few linked/downstream libs...

**Comment by duncan3dc** [comment]
I've just released 1.0.0 that provides PHP 8.0 and 8.1 compatibility now, thanks for your help!

**Comment by dutchie027** [comment]
Awesome. Will you be doing similar for the actual Sonos library (and it's dependent libs)? Happy to help with this also.

**Comment by duncan3dc** [comment]
Yep I'm working through it 😃

**Pull request closed without merging**
